### ISSUE TITLE
Move dual_set to MOI

### ISSUE THREAD

**Issue by guilhermebodin** [guilhermebodin/Dualization.jl#25]

**Comment by chriscoey** [comment]
[Here is an example](https://github.com/JuliaOpt/SumOfSquares.jl/blob/e2286d0fee01fdeb7bc2d9e846d9c6f2ff1c4df6/src/sos_polynomial.jl#L16) of a package defining its own cone type as a MOI.AbstractVectorSet.
[Hypatia also has several cases like this](https://github.com/chriscoey/Hypatia.jl/blob/3cd40957b8863d3cf47b77966d6b515b0449f2fb/src/MathOptInterface/cones.jl#L10) too (and will have more in future).

**Comment by chriscoey** [comment]
So allowing Dualization to be a bit more "generic" (relying less on functions hardcoded for specific cones) might be good.

**Comment by guilhermebodin** [comment]
Nice! I am going to try to remove every specific cone functions, I think I should be able to get everything only using MOI once the dual_set function is there

**Comment by guilhermebodin** [comment]
Already started the PR https://github.com/JuliaOpt/MathOptInterface.jl/pull/804
